import './blocks/intro.js'
import './blocks/tariffs.js'
import './api/map.js'
import './blocks/gallery.js'
import './blocks/instagram.js'
import './blocks/order-modal.js'
import './blocks/feedback-modal.js'
import './blocks/header.js'
